steps:
  publish:
    when:
      branch:
        - main
        - vanilla
    image: harbor.smthd.com/cloudflare/wrangler
    commands:
      - .cicd/publish.sh
    secrets:
      - cloudflare_account_id
      - cloudflare_api_token
