steps:
  publish:
    # when:
    #   branch:
    #     - main
    #     - test
    image: harbor.smthd.com/cloudflare/wrangler
    commands:
      - .cicd/publish.sh
    secrets:
      - cloudflare_account_id
      - cloudflare_api_token
